updated main.yaml (#3)
updated main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -21,21 +21,45 @@ jobs:
         with:
           node-version: 18
 
-      - name : Npm Install
+      - name: Npm Install
         run: npm install
         
-      - name : Lint
-        run : npm run lint
+      - name: Lint
+        run: npm run lint
         
-      - name : Test
+      - name: Test
         run: npm test
         
-      - name : Check Path
+        # Generate sonar-project.properties dynamically
+      - name: Generate sonar-project.properties
+        run: |
+          echo "sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > sonar-project.properties
+          echo "sonar.organization=${{ secrets.SONAR_ORGANIZATION }}" >> sonar-project.properties
+          echo "sonar.sources=." >> sonar-project.properties
+          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
+
+      - name: Check Path
         run: ls -la && pwd && ls -la /
-      
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        if: success() || failure()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+
+      - name: SonarCloud Scan 
+        uses: SonarSource/sonarcloud-github-action@master 
+        with: 
+          args: > 
+            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
+            -Dsonar.pullrequest.branch=${{ github.head_ref }} 
+            -Dsonar.pullrequest.base=${{ github.base_ref }} 
+            -Dsonar.pullrequest.github.repository=${{ github.repository }} 
+            -Dsonar.pullrequest.provider=GitHub 
+        env: 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          
+#       - name : Check Path
+#         run: ls -la && pwd && ls -la /
+      
+      # - name: SonarCloud Scan
+      #   uses: SonarSource/sonarcloud-github-action@master
+      #   if: success() || failure()
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
